### ISSUE TITLE
Use a Markov Chain to Generate Compliments

### ISSUE THREAD

**Issue by Cryptoc1** [trmml/cameron#1]
Wouldn't that be some cool shit?

If only I knew how to do that...

EDIT 1:
Found some things that could help.
  * [https://github.com/soops/sentimood](https://github.com/soops/sentimood)
  * [https://github.com/thinkroth/Sentimental](https://github.com/thinkroth/Sentimental)
  * [https://github.com/prodicus/vocabulary](https://github.com/prodicus/vocabulary)

Last one is Python, but we could probably find a port, or use calls if we _had_ to.

EDIT 2:
More resources.
  * [https://www.npmjs.com/package/markovchain](https://www.npmjs.com/package/markovchain)
  * [https://github.com/substack/node-markov](https://github.com/substack/node-markov)

This one is a more in-depth article about how they work/how to implement them in JavaScript, but is probably overkill for such a project.
  * [http://www.soliantconsulting.com/blog/2013/02/title-generator-using-markov-chains](http://www.soliantconsulting.com/blog/2013/02/title-generator-using-markov-chains)

EDIT 3:
To feed the chain, you could use your array of sayings you already have, but also have it so people can submit other forms of compliments. To make sure people don't abuse the ability to submit compliments (a.k.a. they try to submit an insult), we could use Ethan's Sentimental port on the user input. All of this on the server-side of course.

**Comment by trmml** [comment]
damn, I love this idea. I'll see if I can add this in the next few days. also the sentimental port ethan made would work well because we could measure the sentiment in the markov chained responses and see if it's sympathetic enough :smile:
